### ISSUE TITLE
10.10.4

### ISSUE THREAD

**Issue by MattTimmons** [MacMiniVault/Mac-Scripts#24] opened 2015-07-01 23:21 UTC
Does this script need any updates for 10.10.4 released this week? I noticed you have a commit about it?
-matt

**Comment by jonschwenn** [comment] 2015-07-01 23:40
Which script?  (the issue is tied to the repo, not a specific file)

I'm thinking you may be referencing disablebonjour.sh but I just wanted to make sure.

**Comment by MattTimmons** [comment] 2015-07-01 23:41
oh, sorry, yes. disable bonjour.

**Comment by jonschwenn** [comment] 2015-07-01 23:43
Right now disablebonjour.sh won't disable anything on 10.10.4 - only 10.6 through 10.10.3. I pushed up an update because I knew the change was coming and I wanted to make sure the script didn't try to edit a plist file that wasn't there.

I'll run some testing on it tomorrow and push up the update for 10.10.4.

**Comment by jonschwenn** [comment] 2015-07-02 13:18
Fixed, Tested, Committed.  Thanks!

https://github.com/MacMiniVault/Mac-Scripts/commit/b9d3b02c430f41dd30155be7419ac75e413bb8a7

**Closed by jonschwenn** 2015-07-02 13:18 UTC
